import { TeamMember } from '../_components/meetTheTeam/meetTheTeam';

export const teamMembers: TeamMember[] = [
  {
    name: 'Leah',
    who_are_you: 'I’m Leah!! I’m from the Chicago suburbs and I worked with Kara (and Mara) at a chocolate shop when we were teens!! I’m chronically online and will make you take shots of Malört for fun.',
    fun_fact: 'One time I got on the evening evening news while drunk and dressed as Sonic the Hedgehog',
    most_excited: 'Warm weather and Fat Tuesdays drinks lol',
    throw_up: 'maybe',
  },
  {
    name: 'John',
    who_are_you: 'John Lynch (Mara’s boyfriend) - From Denver, CO - I coach swimming!',
    fun_fact: 'I almost fell to my death off the side of a mountain one time!',
    most_excited: 'Gambling 😈',
    throw_up: 'maybe',
  },
  {
    name: 'Mara',
    who_are_you: 'Mara :) I am kara’s illinois bestie. Franklin Middle School gang. Little known fact is that I am semi responsible for getting kara her job at Grahams… Jodie absolutely hated me but at least I procured her angel Kara who was A) better at the job and B) less annoying. I live in Denver now and work in HR 🙃 ',
    fun_fact: 'I met Bill Murray ',
    most_excited: 'most excited but also anxious for going out because I’ve never been to a big club lol',
    throw_up: 'maybe',
  },
  {
    name: 'Adarsh',
    who_are_you: 'I’m Adarsh! I work with Jackie and I’m from SB. I am great at most things, and plan on losing all my money in Vegas',
    fun_fact: 'I have a dimple on only one cheek',
    most_excited: 'Casinos and clubs!',
    throw_up: 'yes',
  },
  {
    name: 'Sam',
    who_are_you: 'My name is Sam and I live in Santa Barbara and I live with the Amazon boys and Kara and I am the token non-Amazon guy friend :-|) I’m from the Bay Area - I work at a small lil defense industry  startup that makes things like phone cases n stuff - I play music - my dream car is a 1989 Honda Prelude Si 4ws - I am left handed - I have never been to Vegas - i am a dog person - I can eat pizzas all the time and not get tired of them - my favorite color fluctuated but typically is blue - I once won second hottest guy on the school bus in 8th grade - I play tennis sometimes - if I could travel anywhere in the world I would prob choose Japan right now (after Vegas of course) - I’m not necessarily scared of height but sometimes when you get up there I’m like “damn I really don’t want to fall right now” - I don’t necesarily buy astrology but I am a Taurus and that seems pretty cool to me - I drive a purple car - I went to college in Spokane Washington and I studied marketing - my favorite trees are redwoods - my favorite architect is frank lloyd wright (basic I know sue me) - my mother is proud of me ',
    fun_fact: 'I have brown hair',
    most_excited: 'I am excited to go with the freakin flow and see what the hell happens',
    throw_up: 'maybe',
  },
  {
    name: 'Kara',
    who_are_you: "Kara! Born and raised in the Chicago 'burbs and now I work as a hospital pharmacist in Santa Barbara! I went to Vegas for the first time for my 21st brithday... which fell on March 14 2020 aka the weekend the entire world shut down due to Covid. Las Vegas 2: Here we go again! ",
    fun_fact: 'I have a black belt in Karate! ',
    most_excited: 'Spending time with friends and getting crazy food, drinks and little treats',
    throw_up: 'no',
  },
  {
    name: 'Julianne',
    who_are_you: 'Julianne/ Mountain View/ finance for tech ',
    fun_fact: 'I’m allergic to corn and vodka',
    most_excited: 'Clubbing and drinking',
    throw_up: 'yes',
  },
  {
    name: 'Jackie',
    who_are_you: 'I made this. Mobile sites suck',
    fun_fact: 'I can control my goosebumps',
    most_excited: 'Le buffet galore',
    throw_up: 'maybe',
  },
  {
    name: 'Jack',
    who_are_you: 'my name is jack. i live in the figgy household. i also work at amazon',
    fun_fact: 'I ended my republican house of delegates members career out of sheer spite.',
    most_excited: '"Go to a nice wine bar!  I want to reenact all of the parking lot scenes from The Hangover.  People watching in a casino.  Nursing an expensive drink after pregaming."',
    throw_up: 'maybe',
  },
  {
    name: 'William',
    who_are_you: 'I’m Canadian (from Vancouver) and I like poutine. I spend my evenings suppressing childhood hockey trauma.',
    fun_fact: 'I made homemade pesto when I was 19 and I’ve loved cooking since. I only feel motivated to cook for other people. If it’s just for me I throw a bag of frozen TJ rice into the microwave.  My parents are deeply ashamed and I think I’m going to Chinese hell.',
    most_excited: 'I want to get off the Strip and explore a bit of old Vegas',
    throw_up: 'maybe',
  },
  {
    name: "Adarsh's Sleep Paralysis Demon",
    who_are_you: "Adarsh's Sleep Paralysis Demon  I came into being ten days after the establishment of hell and basked in the fire of agony for the first four thousand years or so. After slowly climbing up the corporate ladder of hell, my career stagnated at the seventh circle. I've decided to take a three hundred year sabbatical and recreationally haunt the humans still on earth with the highest potential for wickedness.",
    fun_fact: 'My favorite food is beans!',
    most_excited: "I've been working on a really intricate night terror for Adarsh on the night ò̴̬̤͕͙̔̓̿f̴̻͝ ̸̼̘̇́ͅṯ̸͉̜͝ḣ̷̄ͅě̸̡̯̮̕͠ͅ ̸̡̻̰̉͜1̷̱̫̯̈5̴͈͍̖̮̽̋͠t̵̛͕h̴̫͓̣͊.̴̼̓ ̵͖̺̖̄͝ͅI̸͙͎̞͛̿͠'̷̧̼̜̀͆͌͌m̷̛̩͂͗ ̶̦̿p̷̧̰̔ủ̵̥͉͔͗̐̉͜l̸̯̹̀l̶̦̼͓̻̂͗͘i̸̛̥͍̱̹̒͠ǹ̸̢̆͝g̴̡̪̣̋̈́ ̷̰̬͌̓̎͝o̷̧͍͐̾ú̷͙͎ṱ̵̡͍͓̾̊ ̷̩̖̯͛͗̓à̶̱̮̒̒̕l̵̒̅ͅl̵̬̱͂̏ ̷͕̩͚̠̾t̵͓̞͊h̵̛͚̪̭̀̓̾e̶̺͊̒̕ ̸͔͖̊s̶̟̬̔͜t̸͙̿͂o̶̳͍̠̐p̵̙̝͕̩̍ṣ̵͆͗̍.̶̺̺̣̞̊͊ ̵̯͋͆̽I̸̜͕̫͊̈ ̵̻̇c̷̨̧̯͕͑̏̐á̴͕̜n̶̜͚͈͎̽̈́̑̏ ̶̯̑̉̐̐u̶̬̝̝̠̓̏̅s̴͖̪̝̾̚͝ú̴̹̯̍̆͝a̵̱̝͑l̶͍̞̹͇̊̎͌l̷̹̟̲̃y̴̖̩͕̾ ̸̗͈͌ḡ̷̢̜̥͒̀̆͜e̴̔̚ͅt̴̖̒̌ͅ ̵̫̞͔̟̊h̷͈̄͑̓į̵̳̓̿̾ḿ̴̨̢̰̙̎̀ ̴̧̙̫͆̅t̴̘̍͑͂͘o̷̡̱͕͗̉͋ ̶̳̐ķ̴̟͙̓͊i̵̧͉̜̐c̴̡͎̽͐̇k̸̝͍͔̳̍̾ ̴̧̙̤̙͋̒̾ḯ̵̡̠̹̈́̈̉n̶̛̙̳͈̯͛̇͋ ̴̫̫̘̱͂̃͠h̴͎͑i̸̢̒̊̀s̸̜̤̣̄̃ ̶̡̰̎s̵̜̊̓̿͒ḽ̶̰͎̏̋̀͠e̸̓͜e̷̢̡͔̍̍͜p̸̣͓̘͍̽ ̶̭͒̓f̴̳̝͇̈́͝ǒ̶͔͔̈̇͝r̵͍̂͆͐̎ ̵̰͙͊̑̂m̷̗̤͎͝a̵̝̳͉͛͐͘ͅy̸̡̜̩̗͛̀̂̌b̶̧̨̫͝ȩ̵̝͍̓̂̎̚ ̵̬̻̘̀a̶̬͊̒͒n̷̡͈̿̽̓͘ h̶͕̼̩͍̳̱̲̯͕̲̟̪̯̻͌̎̐̐͑̃̂o̸̮̠̟̐̏̒̃͜͜u̵̡̡͕͙̩̇́̄̈́̓́̈́̏̈́̿͋͘͝͝r̴̞̀̓ ̸̡̝͈͙͇͚̘̫͎̖͕̪̎̂̑̀̎͂̒͂̽̆̆̇̃̈̕ẗ̴̥̗̤͈̪́̅̑̒͌͆̿ơ̷̠̻̠̲̄̚p̸̧̨̢̛͇͓͈̙̜͇̤̑̈̿͐͐̈̃̎̊͛́͑̚s̸̨͕̺͉͈̯̯͈̘͖͕͕̔͛͛͑̒̃̆̈́̉ͅ,̷͇͑͗̊̽͝͝ ̷̭̻̞̘̠̳͇̱̥͕͉̬̥̊̈́̏̎̏̈̃͗̐̏̍̄͝b̵̛͚̜̉̇̇͂̋̿́̄͋͛̃̚ư̸͈̻͉̪̠͖̳͍͇͕̲̩̏͌̚͠t̴̞̤̫̝̖̏͝ ̷̭̐̇̍̌I̸̧̬͉͈̦̻̭͈͚͕̥̟̯͈̍'̸̩̰̘̪̬̜̀̒̊̾͝m̶͓̦̤͇̉̎͗͛̑̃ ̷̝̠̮̹͚̘̼̖͋͋̃́́̍̓̚͜s̶̢̭̱̜̠̹̗̦͕͎͇̎͐̐͐̓̊̅̽͋͐̈́ͅu̴͎̭̫͙̰̤̥̦̳̦̩̜̼͋̏̽́̎͆̅̂̀͋̐̒͗̕͘ͅř̸̨̰̘̱͕̠͉̹͘͜ę̸̱̬̮͍̦̻̱̘̫̻̬̞̈́͋̿͑͋͆͑͠ͅ ̴̮̈́́̾̌́͆̽̉̈́̓̂̓h̵̭̪̙̖̤̜͎͈̼͉̭͇̹͋́̆̈̂̉͗̚͘͜ͅȩ̴̝̮̯̙͙̰̠̫͉̦̊̄̊͒̾͌͗̈́̆̓̚ͅ'̷̛͓̻͍̺̜͕͆̃̈́̎͐̋̒̄̈́̂̏́́l̸̢͙͉͉͉͎͙̦̘̗̾͛́̂̏͠ḷ̸͓̹͖̬̘̻̯͈̠̹̳̏̈́͒ͅͅ ̴̡̡̙̖̣͙̹̺̲͎̜̲͔͖̅̎̂͘ͅb̷̢̛̛̙̳̦̞̙̖̝̭͇̖̱͇͂̔̅͒͌̀̈́́̌̅͂͜͝͠ͅẹ̷̡̢̜̗͓̗͈̜̦̱̯͐̑̂̋͒͐̈́͛̏̌͘͠ ̵̨̧̨̧̯̳̬͔̞͕̬̅̃͂̔̏͗͂͊̑̋̈͑ͅf̸̧̱̦̯̩͖͈͓̫̮͕͇̲̯͒͗̄̓̐̏͜͝ȗ̶͈̫̯̱̠̻͔͍̲͈̈́̊͐l̸̙̹͚͍͖͙͇̘͍̐͜͠͝ļ̴̩͐̋̀̚ ̴̟̭̜̩̘͇͉̗͕̘͈̝̉̐͛̓͐̅̅̊̒̍͘͘͜š̴̘͙̙̼̠̹͎̩̯͋̂̈͆͘ͅl̴̡̗̬̗̈́̓͊̓͗̿̊̆͂̾̀̐̐͘ȩ̶̛͇̗̱͈̦̩̝̭͉̎̄̓̕ͅe̴̡̧͕̘̜̦͚͙͇̻̻̲͆̔p̴̞͍̉̉̑̀̅͠͠͠w̸̧̉̌̓͒͐͋͛̒̔͋́̚͝͝ą̶̪̞̜̺̥͚̈́̀͆̓́̎̄̈̽͘l̴̢̢̡̠̖̲̹͚̼̬̈́̽͐k̷̨̧̰̼̗̙͖͇̳̾̽͌͑͊͂̀̐̃̂̇͝i̵̬̱̦̝͙͓̠̎͛̀́̕ͅn̵̛͗̉̀́͒͐̐͘͝͝ͅg̷̜͙̳̠͕̟̤̖̹͉̼̝̘̣̭͐̀ ̷̧̛͉̻͕̭̲̱͕̳͈͛̓̊̏̈̔͐͝B̴̡͔̫͉̫̖̬̘̗̰̠̔̅̓̅̓͌̐͐̑̈̇̓͝J̷̢̜̺̲̼̜̣̲̣̣̹͕̾̆͆͌͆̔̐̆̿͜͜͝J̸̨̫̟͗͂̒̑́́̈́.̸̡̢͙̗͈̲̻̫̣̫̲̥͚̔͘ ̵̧̛͇̘͍̗͖̞̇͂̌̀̈́̑͋̎̎̿͗͝Ẅ̷͔̝̖͛̊͋̌̄̒i̵͉̦̣̪͓̦͇̻͉̮̬̙̇͌̉͑͋̄͗̚͜ͅl̵̢̡̡̜͕̜̲̣̣̦̓͜ͅl̶̢̨̩͖̯̗̰͇͔͍͙̩̤̈́̾͛͠ͅͅȉ̷̢̛̝̯̱͇͂̾̎̉̇͘̕ă̸̝͆͋̌̀͐̿̈̉͂͘͠͠͠ͅm̸̨̜̌̇ͅ ̷͓̇̉̉́̋̉́̈́͜b̷̢̛̹̲͙̝̱̹͔̭͉̫͍͖̑͆͑͒̉͋̓͂̋̕ͅͅẽ̸̛̪͇̦͖̪̯͇̝̩̮͈͕͒̀̌̈́͋̕͜͠͠t̷̜̙̺̞̝̠̰͕̿͆͗͛͌͋͛̇̆̈́̀̇̒t̷̛̪̥͌̋̂͊̊̀̈́̚͘̕̚ę̴̨̭͚̻̮͚̠̄̅̀͝ͅr̶̡͈̘̫͈̦̜͍̮̖̆̈́͗̋͒̅̋͂̈́͛̈̚͠ ̷̙̙̥͒̅w̷̧̢̝̻̞̠̯͑̋̄̄̕͝͝à̶̧̡̤͚͚͍̝̤̝̯̲͓͍̥͍̑̈́͛̑͑̾̇̀̐͘͘͘͝͝ť̵̫̦͊͂͆̄̑́͆c̴̭̻̑h̶̡̭̭̩͖͈͚̻̯̬̳̅̆̒̈́͛̕ ̵̨̡̤̼̮̻̪͖͙̜͇̪̟̦̫̎̎͐̈́̕ò̴̬͙̣̻͒͛̍͋͌͑̅̚͝u̷̟̰͓͔̝̳̥̖̯̱͕͊̐̈́̄̉́̀̔̚ť̷̫̻̜́.̷̢̬̠̯̯̖͉̫̬̳̖̫̊́̅̾̄̕͝ͅ ̶̢̢̣͎̦͙̹̹͙̫̤̮̣̝̯̄̕͝I̵̧̛̞̞̋̇́́͆̑́̈́͌̾͒̃'̶̨̢͔̬̟̠̭͓̓͌̾̌͋̀̈́̆́̅̋͗̈́͛͠m̵̨̢̡̖̱̤͇͉͛̐͗̄̉͐ ̵̯̜̫̩̂̀̂̍̎̾́̈́̽̒̚͘͠ ţ̶̛̯̦̬͇̼̤͖̠̮̰̯̙̔̎̓̿̀̆̐͑͐̿̑̎̌͑͐̀̚͠ȁ̸̧͈͚̙̓̓͛̂̆̚k̴̡̛̻͙̜̳̪̳̖̋̆̄́̌̂͌̕i̸̡̛̛̬͎̘̩̣̓̓͂͒̆͑̇̐͆̿̈́́̋͝n̷̛̛͚͆̇̇͛́͛̐̊̈̕͝g̵̛̥͖͍̦̰͙̿̓͛͋̈͌̂͌͒͒ ̸̡̤͕̳̩̘͕͎̫̟̥̘̮̃̅̈́͐̋̐̈̈́̈́̓͋͘̚͝͝w̷̯̩̣̦̬̭͕̘̰̗̮̱͚̱͒̈́̀̇͑͜ȩ̸̲͈̰͎̟͍̹̺͇̌͆̈́̕ă̵̙̜̺͍̣̳̪̖̗̔͛̎͆̚͝ŗ̶̧̹̪̱͉͙͖̬̙̹̹̭̭̗̘͚̊͒͑͋͌̂̔̏̚i̶̡̧̢̼̤̘͓̥͖͈̬͚̬̠̠̮̊́̐̄̈́̑͋̋́̋̋̓͂͘̚͝͝ͅͅn̷̮̘̲̤̥̝̞͙̥̱͙̝͕̹̞͖̤̰̯̂͗ͅͅg̷̦͎̬̼̫̘̮̪͈̦͆͊̍̊͊̓̂́̃̽͛̈́̕͘ ̶̨̧̦͙̬̟̩̞̥̗̭͇̪̥̲͉̑̓̈́̾̈̂̾̈͊̀̽̀̄̌͝ͅf̴̨̢̖̰͇̲͙̹̺̣͖̖͉͋̀̈́̾͊̌͂̿̍͗̾̏͐͘͝ọ̴̡̥̹͔͚͈͖̿̅̏̇̑̉̅̄̉̓͒̈͠ớ̷͓̰̳̰̉̍̄͌̽͆͑̏͌̇͑̀̕͝t̸̢̡͍̲̫̲̟̞͖̲̝͑̓͜b̶̠͇͕̙̻̻̝̣̫͉̞̻̼̏̏́̊̆̏̒̈̆̈͘ͅa̵̢̧̡͙͍̗̗̱̞͆̀̅́̀̈́͛̌͆͐͘͠l̸͍̞̦̳̫̯͓̻̥̝̜̫͇̦̱̽͗̔͑̇͘͜͠͝͝ḷ̸̌̀̍̊̅̉̄̈́̓͌͛̇͜ ̶̛̥̦̜̟͕̹̝̭̥̯̙͔͇̣̳͙̭̩͆̃͂͋̃̐̄̀́̎͊̒̾̑͗͋͐͘͝p̴͖͍̟͖̭̻̪͖̯̹͇̤̟̝̈̓a̷̡̧͔̍̋͋̍́̾̓͑̋͋͑͑̂́̿ḑ̶̟̞̥̠͙͍̣͎̩̹̱̗̾͆̀̀͂̔͛̆͜͜ͅs̸̫̟̺͕͚̺̰̩̝̹̝̮͈͑͌̈̿͗͊̌̾̍̓͘̕̕͘͝ ̵̢̧̨̨̛̠̬͚̖̖̗͚͎̟̮̲̗̞̑̄̀̓̈́̄͗̿̇͌͒̇͗̆̚͜͝t̴̢̨͙̤͍̞̝̪̥̻͔̟̥͇̱͓̖́̈̌͒̇̓́͆͋̋̃̄̎̇̃͒̓̕͘͜͝͝ǫ̸̪̱̤̜̪̪͍̹͔̱͙̹͇̟̯̫̭̻̦͛̐̅̂̉̒̎̓͒͜͝͝ ̸̤̲͕̝̗̦̈͊͒̾̋͊̊b̵̢̛̘̤̤̖͙̖̰͈̗͔̹͂̓͋̀͋̉́̆͊̆̑͛̀͛͌͘͘͘è̸͈͐́ḑ̷̧̛͍̰̪̣̺̪̱̰̫̦͔͚̰̞̯̫̖͚̀̃̉͊̇̿͛͜͝͝.̸̧̡̛̞̲̣̩̝̟͖͖̫̫̲͓̫̎͑̅́̐̏̌̀́͒͋̎͑͛͐́̋́́̈ ̷̡͙̲̗̬͈̪͙̯͍̿́͌̈́̽́T̶̢̡̛̟͉̳͖̫͉̬̜̼͕͓͑̑̂͐̏́̈́̇̾̿͋́̑̃͛̏͜͠͝h̶̡̨̛̺͙͇̝͙̹̻̝͍̱͕̩̗͓̞̹̦͓̋̏̂̋̈́̋͛̄̕͘̕̕͠ͅe̸̩͈͎̥̒̐̀͊̎̏͂͆͆̏̓̌̒̊̋̏ ̴̭͔̐̃̅̈́̍̍̽͂̊̋͒̄̃̃͝͠͠d̶̠͇̙̭͈̭̠͙̘̬̭͋̍͋̾͊̂̉́̊̌͝ö̸̪̻͈̩̬̝͇͚͓̝̳̪͚̲̭̾̀̏̋́͛͜͝g̶̛̙̅̓̃̆̓͒͒́̇̃͝ ̷̧̡̦̞̝̭͓̥̀̌̿́̇̓̓̽̉͠ĭ̸͈̫̙̟̈́̐̔̀̀̅͑̑̈́͋̌̓̓̚͝͠ņ̷̖͕͍̰̳̮̺͍̀̏̊͊́̓̓͒́͑́ ̴̮̣͓͙͔̘̱̗͇͔͔̪̪̭̥̦̌̎͐̈́̽͊̂̃̃̍́͒͒́̈́̀̀̚̚͠͠Ȁ̸̧̱̞̬̤͖̺͍̓͐̀̆̄̏̽̄͆̃͑̓̏̂̐̄͠͝d̸̛͉͍͕́̆̀͋͋̈́͠ǎ̶̡̭̮̱͕̹͖̙̖̹̯̟͓͖̗̰̼̺͌̅̐̏̌̂̕͝ŗ̶̛͓̖̫̏̓̔̾̀́̃̐̓̽̾̽̈̋̃͋̚͝͝s̶͓̼̤̱̗̠͇͍͙̩̬̠̹̕͜ͅh̶̨̧͓͔̥͈̞͓͈̘̳̒͐̎̒̚̕̕͜ ̷̡̘̩̥͓̼̞͔̲̱̪̥͙̹͖̑̂̔w̶͇̟̗͚̜̪̝͙̝̳͍̥̘̪̹̾̍̊̉̐̃͘ͅi̸̢̪̻̱̝̖̣͔̬̟̘͔̾͐͒͂̃̎̓̾̐l̵̢̢̛̙̩͇̤̜̗̻̞̪̳̝͇̮̭͇̏̽̓͐͊̽̀̏̾̾̇̋̈̇̚͜͠l̴̨̢̹̞̹̣̯̽́̋ ̷̼̮̪̪̠̆͊͂̋̀́̐̾̐̈́̊̓́̔̔̓̑̓̕̚b̵̢̘͉͇̬͍̼̖̟̲͍̘̲̼̥͝ͅe̷͇̟̗̳̤͉̘̤̥̱̖͚̅̄́̑͌͆͜ ̸͈͇̞͓̭͓̥̤̼͎̀̈͋̆́̂̃̈̽͗̾̈́́̊̑̀̕͝ų̷̡̩̠̱͕̮͈͍̖͖̼͔̃͗́͐̊̐̆̊̍̿̇͒n̵̼̰̾̒͊̓̅͒́̉̀̚͝͝ľ̴̛̛̺̙͈͓̰̗̮͇̼̺̺͙̩̰̱̗͇͎͚̑̅̚̚͝͠͝ḙ̷̖̠̬͔̦̼̣͖̗̟͎̰̮̮͇͌͆̏̉͂̄͑̈́̂̿̍̎̕͝͝ą̵̞̙̩̮̥̰̪͓̞̣̠͔̭̀̌͑̿̾̓͘̕͜͝s̸͈̞͈̙̖̹̠͓̲̤͕̯͒̔̌̕̚̚̚h̴̺̫͉͙͎͔̜̮͌̔͋͒̂͛̂̓͠e̵̥̗̳̣̝̩̰͎̫̰̒̆͆̐̏͘ḏ̵̢̧̢̨̧̘̗̜̪͍̥̜͚̯̙̞̞̀͆̎͗͐͒̅̈́̍̽̒̊̀̚.̷̧̛͈̙̪̞͓̠͎̜͕̘̄̏̍̔͋̈́͐͐̈́͋͆̐̋̒͝ ̵̢̡̠͖̘̩͓̠̖̩̪̫̥͙̃̾̀̌̕T̸̢̢̟̼̲̦̻̣̘̣̳̳̲̩̟̪̠͙͔̜͒̓͗̈́̏̀̏̑͐̃̏̋̀̐̂͋̆̕͘h̷̡͕͍̹̰͉̻̠̝̟͈͈̜̰̼̖̠̉̀̔͐̿̆̀͐̃̑͛̈́̀̐͌̂͐͗͜͠ȩ̷̻̻̤̥͓̗̈́͋͂̈́͋̎̄̅͊͑͛͌́̀̕͘̚͝ͅ ̶̧̛͚̤̦͔̭̯̭̖̗̻͙͓̠̍͒͊̊̽̽̊͆́̅́́̀̔̐̾̉̚͠ḑ̴̠̑̈́͑̔͆̒̅̑̀̈́̍̑̀̾̎̋̕̚̕͠͝ó̵̧̢̲͈͕͈̖̪̦̮̳͈̺͕͋͑͊̏̒̏́͐͑͂͂̍̊͘͘̕͝g̶̛̳̘͈̞͆̋̐͒͗̅̀̿́͒͆̅̿̉͝ ̷̠͙̣̗͎̳̭̻̀̄i̸̧̨̲̞̭͈̗̗͉̍͂̋̒̀͐̽͆̆̎͑̐̑̀͘̚ň̸̡̗̰̩̭̭͇͒͆͌͗́̓͂̉͐̈́̒̈̈́̀̉͘ ̴͙̱̯̪̻̰̼̌̇͝ȟ̸͎̠̼̠̠̮̬̠̦̼̺̩̯̪͖̻͖̠͈̝̂͐͑̓͒̀͊̓̌͑͊͛͐̈́̚ͅi̷̝͕̣̼͙͇͈̼̜̮̤̞̝̝̤̰̗̰̋̈̀̔̽̂̓̕͝m̵̨̠̲̺̞͙͈͉̖͓̞͈̝̈́͆̀̏͘̕.̸̡̩̳͚̳͙̮͚̞̥̝̦̪̹̞́̃̽̀́̔̔̔̍̈́̿͂̾̽͊̈́̆̀͘̚͜ͅ ̶̛̮̓́̿̿͑̓͛̈̐͛͆͊͗̿͂̅̉̅̕͘T̶̨̨̨̘̱̱̘̹̱͉̩̙̝̝̂͛̓͗̌̓̏̽͑͌̉̎͌͋̎͗̕͘̚͜͝ͅȟ̵̨̛͔̪̺̬̺͇̩̃̑̊͋͑̏̅̇̌͗͌͛̌̈͠͝e̷̢̯̖͚̱̯͔̟̘͙̖̬̘̩͈̟̫̹̞͌͐̍̃̔̒̈̓̉͜ ̵̢͓̫̙͔̺̥̬̣͈͕͙̼̦̫̰͔͂̀̂͊͆͋̈́̈́̆̿̎̕͘͝͠͝d̵̙̝̭̙̳͔̲͕̂̎̄̈́͗̒̓͋͆͗͠ͅŏ̸̬̣̥͇̻̜̂̃̂͂̎͜g̶̢̨͙̘͓͍̟̮̘̘̗͍̼̟͖̼̥̦̈́͒̇͆̒͐̇͛̈́̏̉̀̿̆̄̿̍ ̷̨̳͎̥͕̀̐̊̌͂͝į̴̡̨̯̖̩̜̥̬̹͚͔͇̘͓̬̄͂͜n̷̡͓̄̽́̍̎̇̍͆́́͂́͐̚̚͘̕͠ ̷̢̛̞̫̻̹͈͍̺̬̮̝̱͆́̊̾̀̾͗̿̈́̒͋̒̈́̇͗͜h̵̡̝͓͓͇͈̋̆͐̈̽͗́̆̊̇͜ḭ̷̢̧̞̹̮͓͖͖͓͓̞̖̞̗̠̭̘͑̈́̆̂̕͜͠͠ͅm̴̩̭̖̜̖͚͚̼͙̗̎̃.̷̢̨̧̫̠͈̙̖̦̠͇̹̘͎̩̓́̈́͒̽̚͝͝ ̴̧̡͎̻̰̼̥̯̦̺̻̯̫̹̟͓̱̟̫̹̇͐͆̽̍͜͝Ṭ̸̨̧̨̳͍̙̱̣̲̜̱̪̞̣̈́̽̄̈́͌͑̏ḧ̸̨̛͈̖͇͎͖̬͇́̍̈́̽̈́̽͐͒̔̈̌̑̈͐̀͋̋͝ë̶̢̡͖͕͍̜͔͚̳̦̣̞̓͒̈̽͋̽͛͝ ̴̟͙̺̻̀̾̂͠d̶̨͍͓̭͉̲̞̱̳̖̫̼̟͍̝̗͍͐̌ͅȍ̵̢̡̢̘̰͖̞̻͖̬͍͍͚͔̼̟̯̯͓̇̍͊͛̀͊͑̚͝ͅg̷̛̛̩̦̺̺̘̰̩̟͓̐́͂̉́͗̅̌̈̈̉̌́̈́́͌̕͜ͅ ̷̨̧̢̣̰̭̥͚͈̐̈͜į̸̟̩̯͈̯͔͛̍̓̉͌̑̑̌̋̃͆̀͝n̷̡̡̰͓͓̥̮͚̬̼͓̪͖̙̜͑͒̉̂̆̈̇̓͒̀̔̆̆́͊̆̕͜͜͝ͅ ̵̧̨͎͎̼͔̣͙̱͚͍̹͎̮̠͓̘̠̯̖̇̓̈͒͒̀̔͗͊͑̓̎͑̿͆͗̐͑͠ͅh̸̘̯̜͈̘̦̻̤̽̽͊̐͂̊͋́͒̄͒̕̕i̷͕̠̮͔̰̥̪͎̣̖̲̮͈͔̖̼͐̌̕͜m̷̢̧̧̧͓̫̻̥͖̯̺̞̙̥͕̃̋̊̈́̎̒̈̒͗̽̔͊̅̄̎̀̄͝͠.̷̗̬͈̙̞̅̈́̏͊͗͒͗͐͌͐͊̋̈́̚ ̵̨̮̰̙̪̖̫̜̬̱̺̼͉̩̳̦̲͓͔̅̀̈́̈̓́̔̓̈́̄̅̅̏͘͝T̷̯͉̐̈́̋̇̽́̓̌́̒̾́͐̔̚͝͠͝ḩ̴̡̢̪̟̘͕̙͔̤̥̙̼̓̽̊̎͆̓͊̇͑̔̋͊̐̈́̃̈ͅȩ̸̪̰͚͔͙̼̐̌̅̀͆̆͑̋͝͠ ̷̢̬̭̦̣̬̩̜̘͕̘̩̲͖̯͙͕̲͕̍̎̍̎́́͗̾̔̐̀́̍̃̿̓͊̊̚͘͠d̵̢̠̠͎̝͋̿̈́̿̐̿̈͒͜͝ǒ̴̡̞̫̭̺̭̙͖̠͉̲̼͔̩͕̙̓͆̈́̅͗͂̈́̈̎́̚͠g̴̹̭̖͉̣͓͎̪̼͎͖̗̹̫̬̹͈̝͈̍̃̌̓̂̿́͋̈́̐̅́͛̚͝ͅ ̷̢̛͎̦̝̈́̌͌̍̽͐̔͂̏̂̀̀͌̄́̂͘i̶̠̪͖͎͈͚̲̰͕̘̰͈̦̊n̵̡̧̫̹̳͔̖̹̺̱̣̰̓̔͌̚ ̶̛̻̱̱̈͂͋̃̿̀́̐͜ḫ̵̡̢̞̯̻̗̹͎̻̭͈̐͒͐̕i̴̺̰͇͐̀͑̂̀̆̅̇̎̆̕͠͝m̸̡̧̢̯͇̤̤̞͚̭͈͇̥͈̯̬̠̪͐͋́̾͒̈̏̆̌͗̈́͑̕͝ͅ.̶̨͚̩̖̪̖͔̣̪̟̺̯͙͕̘̦̱̹̓͌̐͑̓̅̉͗̾̂̅̀̍̈́͘͜͝͝ ̸̹̜̦̗̉̚T̸̞̏̈̈́̊̾̈́͆͑̏̽̔͐́͝h̷̻̮̝̮̤͑̔̑̏̓̾̓͛͗͌͊̈̈́͌͛̋̚̚͝͝ͅͅe̴̱̪͕̫̦̮̜̬̠̝̗̫̼̿̇̌ ̷̧̠̤͕̬͕͍͉͎͐̄́͆̐̌̈́́̂̈͛̑͠ͅd̸̡̧̻̣͈̙̪̙̹̮̹̤̪̿̀̊́̔͑̎́̀̃̀̉̇̃̀͘ó̸͓̠̙̏̎̓̓̽͆̃̾͌͘̕͠͝ͅg̶̨̳̹͉̩̲͚͓̲̼͕̞̒̿̍̑͒̽̓̏̉̒ ̷̨̨͖͇̥̻̞̥̭͇͈͉͕͕̼͓̻͈͈͖̔̀͒͝ȋ̵̛̛̘̼̩̯͇̻̗̪̞̺͇̘͕̙̪͆̉́͛͋͑̽͜͜n̷̨̛̯̝̦̯̹͓̝͈̙̗̘͉͎̲̩̹̝͓̙͗̽̍͑̇͒͆̈́͛̃͜ ̸͍̻̽̑̽͐̀̈̇̐̐̒̽̽̑̌͑͘͘͝ḩ̸̹̼̯̝̯̤͎̬̻͎͈̈̇ͅi̷̢̨̨̧̨͖̣͍̮̠̬̟̦͕̣̞͍̗̓̏͌̀̕͠ṃ̴̧̛̛̳̫̰̯̳̅̌̊̓̋̆̑̓̃͒̉͛̈́̂͋̕͘͝.̵̧̧̛̤͕̻̠̳͓͙̟̩͓̠̦̪̎̉̇̏̑̈̐́ͅ ̵̢̣̲͔̘͖̗̰̦͚̤̜̓̅̃̿̔̒̽̑̄̾͘̚̕͜T̴̨̢̹̰̳̣̩̰̠̲̗̦̫̿́̌̓̃͆̂̾̐̽̅́̀͜͜͠h̷̡̢̧̡̼̗̬͍̺̖͉͉͔̼̮̲̜̝̬̹͉̍ę̵̢̟̺͍͇͎̼̪̱͕͎̠̰͕͊̈́͊̒̋̀̕͠͠ͅ ̵̛̖̰̻̺̜̝̟̤͔̜̈̐̇d̵̨̛̰̲̦̯̪͂̔̓̉͗̊̌̓͌̽̅̇͝͝ǫ̶͕͚̯̼̟͇̦͖̫̊̈́̒̎̅̆̈́̈̈̑̎͒̑̏̈́͂̕̚͜͝ģ̵̮̭̠̝͇͔̰͇͇͍̻̹̆̅̔̓̽̈́̅̈́̚͠ͅ ̷̛̣̯̥̣̒̋͗̀́̿̔́̈́̐̽͘̕͝ǐ̴̜̫̬͉̞͍̺̮͈̟̜͇̬̬́̍̔̍͌̀́̈̏̐͛̄͊͆̾͗̿̽̍͜͝ͅͅn̶̡̺͙̯̮̤̰̽͗́̈́͐͑̿̐̀̎̀͌͊̉̕͜ͅͅ ̵͎̬̺̼͎͈̻͈̂̈̽̏̇́̔̌̂̋̇̎͛̕h̷̨̧̛̙̮̺͔͙̠̥̱͇̪̩̆̍̓͌̇́͌̆̐͌̓̓́̈́̑̒̕͜͝i̷̧̨̲̫̥̯̼̝̻̤͈͚̼͗̃m̸̛̛̖̦̥̯̩͕̮̟̫̀́̈́̿̒͌̊͛̚͝.̷̨̨̣̮̟̬̻̹̦̮̞̼̯̬͓̓̉́͆ͅͅ ̷̡̡̛͕̮̙͇͈͇̫̗̯͙͎̈́͛̍̔̔̆̈́͒͋̍͊́̋͑̕͝Ţ̴̞̹̹͇̫͎̉̾́h̵͔̺̖̖̜̾͋̐́̈́̇̋̀̈́͝͝ȩ̸̧̦͈̦̩̤̼̰͙̞͈̺͇̾͜ͅ ̸̧̨̢̼̠͙̯̩̞̘͕̬͎̭̳̯̖̫̣͉͆̆͜d̶̡̺͕͉͊͌̾͒͛̐͑͛͗̈́́͜ó̸̧̥̖͎̟͍̞̂̓̊̋̋͋͒̅̓̽̉͝ģ̷̛̠̖̠͔͈̯͍̺̠̞̿̔̅̌̓̀́̾͆̍͆͆̄͌̒̑͂̇̕͘ͅ ̸̧̛͖͚̬͈̣̼̺͍̲̊̿̔͋̒̎͋̂̑̂̓͊̍̋̍̀͘͝i̴̤̣̯̐̃̂̂̿̒̄̈̓͋̏̍͘͝͝n̴̛̤̣͙͓̫̆͌͌̀̃̒̀͐͒̅̉͋̏͒̒̈͘̕͝ ̴̡̢̢̛̱͖̞͙̱̟̠̙̫̘̯͓͉̦͖̫͕̩̀́̀̒͑̚͝h̷̨̧̛̥̠̘̯̖̤͖̟̟͕̖͚͍͓͚̫̖̃̒̇̈̂̿̏͑͊͘͘ͅi̶͎̣̙̬̫͋̐̒́̀̐m̸̧̧̛͈̦̩̗̫͔̘̫̰̭̏͌̽̅͛̒̋͑̉͐̀͑̂͌̕ͅ.̸̡̪̼͓̜̫̫͉͙̙̦̦̠̩̞̲͎̍́̒̽̃̈́͘͜ ̷̦̈̃̅̈̋̽̄̉̓̓̊̒̈́̌̌̕͝͝T̵̨̢̡̧̺̟̘̟͉͙̮̯̩̗͇̞̑͜ͅh̴̢̘͕̮̼̻̬̲͒̇͒̆͛͑̊̓̓̒͋̒̒́̓̇͝ͅe̵̛̤̪͓̳̣͎͚̽͑͛̍͗͑̀̑̌̆̓͠͝͝ ̷̧̛͍̙͚͍̤̦͔̗̬̟̤̰͈͙̆͋̍̅̈́̈́̐̋̃͘̕͘͠d̸̨͕̥̃̈͐̂̇̒̀̽̓̒̋̾̄̃́̎͆̕͝ǫ̵͈̞͎̻͍̹̟̞̇͊g̷̡̢̢̮̮̺͔̯͍̻͙̺̲̠̟̰̠̱̭̍̓̒̑̔͑͆̓̉̀̕̚͜͝ ̶̢̡̡̛̼̠̰͉̝̗̙̪̹̠́̏̅͛͗̉̎͂̋̋͋̒͘͘͜͠͝͝i̶̧͓̘͉̙̬̼͔̍͂͝n̵̙̠̭̳̝̥͚̑̈́̈́̇͆̇ͅ ̷̧̨̫̙̝͇͍̥̰͓̹̜̠̟͇̤̺̩͔̋̍̉̿̚͜ḩ̵̡̖̲͖̱̹͉̭̠̰͇̘͉͉̞̈́̎̀̂͌̌̎̈́̑̍͑̀̿̔̚͠į̸̨̛̹̼̭̰̦̲̙̠̯͖̬̯̓́̊͋͐͋̅̎͊̽́̈́̊̑̍̕͠ͅm̶̡̡̩̠̣̱̙̰̲̺̹̬͉͍͓̈́̄̂̈́̾.̵̛̗̻̘̎̌̀̏͑̈̀͗̌̑̑͗̐̓̆͐́͛̚͝ ̶̭̰͎̙̥͚̫̫̩̜̮̮̥͈̞̦͖͍̐̀̍̎̎T̷̨̼̞̟̩̻̠͎̘̦̻͇͕̻̲̩̠͙̣̂̈́̐̍̽̑̽̑̀̿͆͜͝͝h̵̰̙͎̗̰̺͇̪̆̌̏̂̄̌̈̍͐̃́͒͒͊͊̀͐̌͝͝ę̶̤̯̮͐̀͆̓̿̇̓̋́̌̈̾̄̑̾̎̚̚͜͜͠͝͠ͅ ̵̢̨̡̪͎̲̳̂̄̃͗͌͝ḑ̷̧̰̗̬͚͍̥͖͉̣͚̙̲̆̓̿̓͐̽̉̉̎͐͒̒̄͗̇͒̏̕̚ͅo̷̹̪͍̔̅̃̈̈́̓͛̈́̔́̈́̒̐̎̑̕g̶̡̛̙͍̪̟̦̫͖̫͓̓̕ ̷̖̫̣̻̞͖̱̻̝̰̦̤͇͆̂̀̒ͅī̸̧̮̞̲͂̿̎́̐̉̇̈́̏̐̆͝n̶̦̬͕̳̫̭̻͗̈́̂̌͐͑ ̸̡̧͉̮͎̮͍̺̻̥̭͍̹͈͉̗̾́͗͊͗̑̊ḩ̴̤͔͎̱̮̽͌̓̂͛̏͛̄̐͐̈͋̕͜ĭ̶̢̧̳̙̦͎͇͓̞̲̳͉̰̻̦̿̿͒͐̓̓̌͒͐̉̃̀̋̿́̌͝͝͝m̴̛͖̺̫̲̤̭̞̰̈̌͑̂͛̿̅̍͋͒̂.̸̳̤͉̳̋̃̌̀̔̀̔̈́̅͂̑̍̓̈́̃̓͒̆͋̚ ̷̡͇̼͖̲̈́̐̂͜ͅT̴̰͎̖̲̪̦̣͒͆̆̏̋̀̀̋͐͂͝ẖ̴̢̭̮̳̦̲̮͇̐͒̉̈́̓͊̆́͊̕͘̕͝é̵̠̒͋͗̊͝ ̴͎̲̊̄̔̋͒̀͛̔͌̀̅͆͊̇̿̄͝͝͝ḑ̶̗̬̳͇̝̣͈͑̅̍̈́́̓̀̓͗̾͜͠ọ̴̜̘͍́̋̐͒̆͆́̓̓̾̅͆͝g̶̳͉̰͇̮̝̺̃̿̏̆̎͆́̎̐̀̾̓̐̀͠ ̵͚̺͙͔̺̯̳̠͈̱͆͊̇̃̍͝i̶̡̡̨̗͈̦̯̭̞̞̼̗͍̫̿̈̔͋̐͂̈́͗̽́͜ň̷̛̪̭́̀̑̈́͐̐̑̈̈́͑̎̈́͘͘̚͝ ̸̢̢̳̞͓̪̖̹̩̬̳͖͕̬͍͈̝͂̀̿͂̉ͅͅh̶̹̰̹̼͎̦̝̺̻̲̝̊̈́̏̀͊̓͌̚͜͜͝i̴̡̫̠̘̮̼̝̼̹̦̤͎̫̹̜̗̇̀̌̍͌̑͝ͅm̷͉͓̬̼̤͊̔͒̓͆̓̚.̸̢̡̛̦͍̺͕̣̫̠̤̳̝̘̼̓̓͗̏̀̽͗̍͐͋̓͘͠͝ͅͅ",
    throw_up: 'maybe',
  },
  {
    name: 'Paulo',
    who_are_you: "I grew up on the mean streets of Texas. Ropin' cattle, building tumbleweed sculptures, I did it all. My first car was a horse. These days I wil' out west.",
    fun_fact: 'I love a good grocery store',
    most_excited: "Texas Hold 'Em",
    throw_up: 'no',
  },
];
